import type { MetadataRoute } from "next";

const BASE_URL = "https://ampliscanner-testbed.vercel.app";

const ROUTES = [
  "/",
  "/no-tracking",
  "/no-tracking/page-2",
  "/no-tracking/autocapture-only",
  "/no-tracking/no-autocapture",
  "/pii",
  "/pii/greeting",
  "/pii/form",
  "/pii/clean",
  "/naming",
  "/naming/clean",
  "/naming/casing-low",
  "/naming/casing-high",
  "/naming/concept-2",
  "/naming/concept-4",
  "/naming/generic-1",
  "/naming/generic-2",
  "/naming/combined-high",
  "/naming/unreadable",
  "/methods",
  "/methods/clean",
  "/methods/duplicate-low",
  "/methods/duplicate-high",
  "/methods/split-no-standard",
  "/methods/combined-high",
  "/legacy-sdk",
  "/legacy-sdk/current",
  "/legacy-sdk/low",
  "/legacy-sdk/medium",
  "/legacy-sdk/high",
  "/legacy-sdk/mixed-floor",
  "/untracked",
  "/untracked/ratio-10",
  "/untracked/ratio-10/page-1",
  "/untracked/ratio-10/page-2",
  "/untracked/ratio-10/page-3",
  "/untracked/ratio-10/page-4",
  "/untracked/ratio-10/page-5",
  "/untracked/ratio-10/page-6",
  "/untracked/ratio-10/page-7",
  "/untracked/ratio-10/page-8",
  "/untracked/ratio-10/page-9",
  "/untracked/ratio-10/page-10",
  "/untracked/ratio-30",
  "/untracked/ratio-30/page-1",
  "/untracked/ratio-30/page-2",
  "/untracked/ratio-30/page-3",
  "/untracked/ratio-30/page-4",
  "/untracked/ratio-30/page-5",
  "/untracked/ratio-30/page-6",
  "/untracked/ratio-30/page-7",
  "/untracked/ratio-30/page-8",
  "/untracked/ratio-30/page-9",
  "/untracked/ratio-30/page-10",
  "/untracked/ratio-60",
  "/untracked/ratio-60/page-1",
  "/untracked/ratio-60/page-2",
  "/untracked/ratio-60/page-3",
  "/untracked/ratio-60/page-4",
  "/untracked/ratio-60/page-5",
  "/untracked/ratio-60/page-6",
  "/untracked/ratio-60/page-7",
  "/untracked/ratio-60/page-8",
  "/untracked/ratio-60/page-9",
  "/untracked/ratio-60/page-10",
  "/pageviews",
  "/pageviews/clean",
  "/pageviews/missing-some",
  "/pageviews/reused-value",
  "/pageviews/proliferation-low",
  "/pageviews/proliferation-high",
  "/pageviews/no-pageview-anywhere",
  "/mechanics",
  "/mechanics/spa",
  "/mechanics/cookie-banner",
  "/mechanics/mega-menu",
  "/mechanics/mega-menu/product-a",
  "/mechanics/mega-menu/product-b",
  "/mechanics/mega-menu/product-c",
  "/mechanics/dangerous-buttons",
  "/mechanics/infinite-scroll",
  "/mechanics/tabs-dropdowns-video",
  "/mechanics/sitemap-only/page-a",
  "/mechanics/sitemap-only/page-b",
  "/mechanics/sitemap-only/page-c",
  "/mechanics/login-wall",
  "/mechanics/login-wall/dashboard",
  "/mechanics/login-wall/settings",
  "/mechanics/drift-redirect",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return ROUTES.map((route) => ({
    url: `${BASE_URL}${route}`,
    lastModified,
  }));
}
